In [13]:
import numpy as np

A = np.array([[1,2], [3,4]])
B = np.array([[5,6],[8,9]])

v_stack = np.vstack((A, B))
h_stack = np.hstack((A,B))

print(v_stack)
print(h_stack)

[[1 2]
 [3 4]
 [5 6]
 [8 9]]
[[1 2 5 6]
 [3 4 8 9]]


In [16]:
import numpy as np

A = np.array([[1,2], [3,4], [7,8]])
B = np.array([[5,6],[8,9], [7,8]])

common_elements = np.intersect1d(A, B)

print(common_elements)

[7 8]


In [17]:
import numpy as np

A = np.array([1,2,3,4,5,6,7,8,9,10])

lb = 5
ub = 10

num_within_range = A[(A >= lb) & (A <= ub)]

print(num_within_range)

[ 5  6  7  8  9 10]


In [23]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

column = ['Manufacturer', 'Model', 'Type']
filter_df= df.loc[::20, column]

print(filter_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [28]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

print (df)

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31

In [30]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

sum_gr_100 = df[df.sum(axis=1) > 100]

print(sum_gr_100)


     0   1   2   3
5   29  34  29  13
6   25  27  21  30
7   18  36  39  35
8   36  19  28  38
9   23  35  34  36
10  32  30  37  19
11  32  27  39  24
